session_name: forge-of-fortitude-blacksmith-of-your-body
topic: 'Forge of Fortitude: Blacksmith of Your Body'
topic_source: manual
mode: standard
duration_minutes: 30
audio_only: false
dry_run: false
execution:
  started: '2025-12-29T00:00:03.274386'
  ended: '2025-12-29T00:37:49.019227'
  duration_seconds: 2265.7
stages:
  completed:
  - create_plan
  - create_session
  - generate_manifest
  - generate_script
  - generate_prompts
  - generate_voice
  - generate_binaural
  - generate_sfx
  - mix_audio
  - hypnotic_post_process
  - generate_vtt
  - generate_images
  - assemble_video
  - generate_thumbnail
  - self_improvement
  failed:
  - upload_website
  total: 16
costs:
  mode: standard
  multiplier: 1.0
  operations:
  - name: manifest_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2025-12-29T00:00:04.837568'
  - name: script_generation
    estimated: 0.35
    actual: 0.35
    timestamp: '2025-12-29T00:00:30.743417'
  - name: image_prompts
    estimated: 0.1
    actual: 0.1
    timestamp: '2025-12-29T00:02:39.379838'
  - name: voice_synthesis
    estimated: 0.15
    actual: 0.15
    timestamp: '2025-12-29T00:02:39.427588'
  - name: vtt_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2025-12-29T00:18:25.785862'
  total_usd: 0.7
outputs:
  session_path: /home/rsalars/Projects/dreamweaving/sessions/forge-of-fortitude-blacksmith-of-your-body
  manifest: /home/rsalars/Projects/dreamweaving/sessions/forge-of-fortitude-blacksmith-of-your-body/manifest.yaml
  script: /home/rsalars/Projects/dreamweaving/sessions/forge-of-fortitude-blacksmith-of-your-body/working_files/script.ssml
  files:
  - output/forge_of_fortitude_blacksmith_of_your_body_MASTER.mp3
  - output/subtitles.vtt
  - output/forge_of_fortitude_blacksmith_of_your_body_MASTER.wav
  - output/voice.mp3
  - output/sfx.wav
  - output/youtube_thumbnail.png
  - output/session_mixed.wav
  - output/binaural_dynamic.wav
