session_name: "journey-to-t\xEDr-na-n\xF3g-the-land-of-eterna-20251204"
topic: "Journey to T\xEDr na n\xD3g \u2014 The Land of Eternal Youth | Journey: You\
  \ pass through an ancient hazel grove and into the shimmering youth-realm where\
  \ time flows like mist. You meet radiant beings who dissolve aging, fear, and inertia\
  \ | Archetypes: The Shining Ones, Eternal Child, The Hazel Maiden | Audio: 4 Hz\
  \ theta; soft fae chimes; reversed harp glissandos; distant ocean-wind"
mode: standard
duration_minutes: 30
audio_only: false
dry_run: false
execution:
  started: '2025-12-04T06:29:12.259493'
  ended: '2025-12-04T07:03:28.136331'
  duration_seconds: 2055.9
stages:
  completed:
  - create_session
  - generate_manifest
  - generate_script
  - generate_prompts
  - generate_voice
  - generate_binaural
  - mix_audio
  - hypnotic_post_process
  - generate_vtt
  - generate_images
  - assemble_video
  - cleanup
  - self_improvement
  failed: []
  total: 13
costs:
  mode: standard
  multiplier: 1.0
  operations:
  - name: manifest_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2025-12-04T06:29:12.259914'
  - name: script_generation
    estimated: 0.35
    actual: 0.35
    timestamp: '2025-12-04T06:29:12.280933'
  - name: image_prompts
    estimated: 0.1
    actual: 0.1
    timestamp: '2025-12-04T06:31:12.973674'
  - name: voice_synthesis
    estimated: 0.15
    actual: 0.15
    timestamp: '2025-12-04T06:31:13.028962'
  - name: vtt_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2025-12-04T06:36:29.089815'
  total_usd: 0.7
outputs:
  session_path: "/home/rsalars/Projects/dreamweaving/sessions/journey-to-t\xEDr-na-n\xF3\
    g-the-land-of-eterna-20251204"
  manifest: "/home/rsalars/Projects/dreamweaving/sessions/journey-to-t\xEDr-na-n\xF3\
    g-the-land-of-eterna-20251204/manifest.yaml"
  script: "/home/rsalars/Projects/dreamweaving/sessions/journey-to-t\xEDr-na-n\xF3\
    g-the-land-of-eterna-20251204/working_files/script.ssml"
  files:
  - "output/journey_to_t\xEDr_na_n\xF3g_the_land_of_eterna_20251204_MASTER.mp3"
  - output/subtitles.vtt
