session_name: echos-from-the-ten-of-pentacles-vault-an-inherited
topic: '- Echos from The Ten of Pentacles'' Vault: An Inherited Wisdom Tarot Meditation'
topic_source: manual
mode: standard
duration_minutes: 30
audio_only: false
dry_run: false
execution:
  started: '2026-02-03T00:23:42.212315'
  ended: '2026-02-03T00:45:16.901382'
  duration_seconds: 1294.7
stages:
  completed:
  - create_plan
  - create_session
  - generate_manifest
  - generate_script
  - generate_prompts
  - generate_voice
  - generate_binaural
  - generate_sfx
  - mix_audio
  - hypnotic_post_process
  - generate_vtt
  - generate_images
  - assemble_video
  - generate_thumbnail
  - upload_website
  - self_improvement
  failed: []
  total: 16
costs:
  mode: standard
  multiplier: 1.0
  operations:
  - name: manifest_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2026-02-03T00:23:43.768495'
  - name: script_generation
    estimated: 0.35
    actual: 0.35
    timestamp: '2026-02-03T00:24:00.962232'
  - name: image_prompts
    estimated: 0.1
    actual: 0.1
    timestamp: '2026-02-03T00:25:53.844672'
  - name: voice_synthesis
    estimated: 0.15
    actual: 0.15
    timestamp: '2026-02-03T00:25:53.898708'
  - name: vtt_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2026-02-03T00:36:35.093368'
  total_usd: 0.7
outputs:
  session_path: /home/rsalars/Projects/dreamweaving/sessions/echos-from-the-ten-of-pentacles-vault-an-inherited
  manifest: /home/rsalars/Projects/dreamweaving/sessions/echos-from-the-ten-of-pentacles-vault-an-inherited/manifest.yaml
  script: /home/rsalars/Projects/dreamweaving/sessions/echos-from-the-ten-of-pentacles-vault-an-inherited/working_files/script.ssml
  files:
  - output/echos_from_the_ten_of_pentacles_vault_an_inherited_MASTER.mp3
  - output/subtitles.vtt
  - output/voice.mp3
  - output/sfx.wav
  - output/seo_metadata.json
  - output/youtube_thumbnail.png
  - output/echos_from_the_ten_of_pentacles_vault_an_inherited_MASTER.wav
  - output/session_mixed.wav
  - output/binaural_dynamic.wav
  - output/product_schema.json
