session_name: constellation-journey
topic: Constellation Journey
topic_source: manual
mode: standard
duration_minutes: 30
audio_only: false
dry_run: false
execution:
  started: '2025-12-14T07:00:02.001624'
  ended: '2025-12-14T07:09:54.106020'
  duration_seconds: 592.1
stages:
  completed:
  - create_session
  - generate_manifest
  - generate_script
  - generate_prompts
  - generate_voice
  - generate_binaural
  - generate_sfx
  - mix_audio
  - hypnotic_post_process
  - generate_vtt
  - package_youtube
  - generate_thumbnail
  - upload_website
  - cleanup
  - self_improvement
  failed: []
  total: 15
costs:
  mode: standard
  multiplier: 1.0
  operations:
  - name: manifest_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2025-12-14T07:00:02.002144'
  - name: script_generation
    estimated: 0.35
    actual: 0.35
    timestamp: '2025-12-14T07:00:28.488349'
  - name: image_prompts
    estimated: 0.1
    actual: 0.1
    timestamp: '2025-12-14T07:03:10.054181'
  - name: voice_synthesis
    estimated: 0.15
    actual: 0.15
    timestamp: '2025-12-14T07:03:10.149115'
  - name: vtt_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2025-12-14T07:08:31.477042'
  total_usd: 0.7
outputs:
  session_path: /home/rsalars/Projects/dreamweaving/sessions/constellation-journey
  manifest: /home/rsalars/Projects/dreamweaving/sessions/constellation-journey/manifest.yaml
  script: /home/rsalars/Projects/dreamweaving/sessions/constellation-journey/working_files/script.ssml
  files: []
