"""
Product Intelligence Schema
Defines the deep thinking artifacts generated by ProductMind.
"""

from pydantic import BaseModel, Field
from typing import Literal


class ReaderAvatar(BaseModel):
    """Who exactly is this product for?"""
    beliefs: list[str] = Field(
        description="Core beliefs the reader holds (may be limiting or empowering)"
    )
    fears: list[str] = Field(
        description="What keeps them up at night related to this topic"
    )
    desires: list[str] = Field(
        description="What they deeply want to achieve or become"
    )
    energy_level: Literal["exhausted", "neutral", "motivated"] = Field(
        description="Current emotional energy when approaching this topic"
    )
    sophistication: Literal["novice", "intermediate", "expert"] = Field(
        description="Current knowledge level on the topic"
    )


class TransformationMap(BaseModel):
    """The journey from before to after."""
    before_state: str = Field(
        description="How the reader feels/thinks/acts BEFORE consuming this product"
    )
    after_state: str = Field(
        description="How the reader feels/thinks/acts AFTER consuming this product"
    )
    key_shifts: list[str] = Field(
        description="The specific belief/behavior shifts that enable the transformation"
    )


class ProductIntelligence(BaseModel):
    """
    The deep thinking artifact that MUST exist before any writing begins.
    This is the soul of the product.
    """
    avatar: ReaderAvatar = Field(
        description="Detailed profile of the ideal reader"
    )
    transformation: TransformationMap = Field(
        description="The before/after journey this product enables"
    )
    emotional_arc: list[str] = Field(
        description="The sequence of emotions the reader should experience",
        examples=[["curiosity", "hope", "challenge", "breakthrough", "empowerment"]]
    )
    thesis: str = Field(
        description="The single sentence justifying this product's existence. 'This exists because...'"
    )
    core_promise: str = Field(
        description="What the reader can confidently expect to gain"
    )
    anti_goals: list[str] = Field(
        description="What this product explicitly does NOT try to do (prevents scope creep)"
    )
