session_name: the-abyss-of-forgotten-dreams-dreamweaving
topic: The Abyss Of Forgotten Dreams Dreamweaving
topic_source: manual
mode: standard
duration_minutes: 30
audio_only: false
dry_run: false
execution:
  started: '2026-01-23T00:42:09.866107'
  ended: '2026-01-23T00:42:47.001036'
  duration_seconds: 37.1
stages:
  completed:
  - create_plan
  - create_session
  - generate_manifest
  failed:
  - generate_script
  - generate_script failed; aborting pipeline
  total: 5
costs:
  mode: standard
  multiplier: 1.0
  operations:
  - name: manifest_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2026-01-23T00:42:11.596575'
  - name: script_generation
    estimated: 0.35
    actual: 0.35
    timestamp: '2026-01-23T00:42:25.065857'
  total_usd: 0.4
outputs:
  session_path: /home/rsalars/Projects/dreamweaving/sessions/the-abyss-of-forgotten-dreams-dreamweaving
  manifest: /home/rsalars/Projects/dreamweaving/sessions/the-abyss-of-forgotten-dreams-dreamweaving/manifest.yaml
  script: /home/rsalars/Projects/dreamweaving/sessions/the-abyss-of-forgotten-dreams-dreamweaving/working_files/script.ssml
  files: []
