session_name: the-aurora-bridge-of-transcendent-flow-dreamweavin
topic: The Aurora Bridge Of Transcendent Flow Dreamweaving
topic_source: manual
mode: standard
duration_minutes: 30
audio_only: false
dry_run: false
execution:
  started: '2026-01-03T00:00:03.351659'
  ended: '2026-01-03T00:38:55.890945'
  duration_seconds: 2332.5
stages:
  completed:
  - create_plan
  - create_session
  - generate_manifest
  - generate_script
  - generate_prompts
  - generate_voice
  - generate_binaural
  - generate_sfx
  - mix_audio
  - hypnotic_post_process
  - generate_vtt
  - generate_images
  - assemble_video
  - generate_thumbnail
  - upload_website
  - self_improvement
  failed: []
  total: 16
costs:
  mode: standard
  multiplier: 1.0
  operations:
  - name: manifest_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2026-01-03T00:00:04.896089'
  - name: script_generation
    estimated: 0.35
    actual: 0.35
    timestamp: '2026-01-03T00:00:31.860463'
  - name: image_prompts
    estimated: 0.1
    actual: 0.1
    timestamp: '2026-01-03T00:02:30.611675'
  - name: voice_synthesis
    estimated: 0.15
    actual: 0.15
    timestamp: '2026-01-03T00:02:30.659426'
  - name: vtt_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2026-01-03T00:14:22.414389'
  total_usd: 0.7
outputs:
  session_path: /home/rsalars/Projects/dreamweaving/sessions/the-aurora-bridge-of-transcendent-flow-dreamweavin
  manifest: /home/rsalars/Projects/dreamweaving/sessions/the-aurora-bridge-of-transcendent-flow-dreamweavin/manifest.yaml
  script: /home/rsalars/Projects/dreamweaving/sessions/the-aurora-bridge-of-transcendent-flow-dreamweavin/working_files/script.ssml
  files:
  - output/the_aurora_bridge_of_transcendent_flow_dreamweavin_MASTER.wav
  - output/subtitles.vtt
  - output/voice.mp3
  - output/the_aurora_bridge_of_transcendent_flow_dreamweavin_MASTER.mp3
  - output/sfx.wav
  - output/seo_metadata.json
  - output/youtube_thumbnail.png
  - output/session_mixed.wav
  - output/binaural_dynamic.wav
  - output/product_schema.json
