session_name: learning-from-books-dreamweaving
topic: Learning From Books Dreamweaving
topic_source: manual
mode: standard
duration_minutes: 30
audio_only: false
dry_run: false
execution:
  started: '2026-01-07T01:33:21.559485'
  ended: '2026-01-07T01:36:35.254640'
  duration_seconds: 193.7
stages:
  completed:
  - create_plan
  - create_session
  - generate_manifest
  failed:
  - generate_script
  - generate_script failed; aborting pipeline
  total: 5
costs:
  mode: standard
  multiplier: 1.0
  operations:
  - name: manifest_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2026-01-07T01:33:23.425362'
  - name: script_generation
    estimated: 0.35
    actual: 0.35
    timestamp: '2026-01-07T01:33:36.129872'
  total_usd: 0.4
outputs:
  session_path: /home/rsalars/Projects/dreamweaving/sessions/learning-from-books-dreamweaving
  manifest: /home/rsalars/Projects/dreamweaving/sessions/learning-from-books-dreamweaving/manifest.yaml
  script: /home/rsalars/Projects/dreamweaving/sessions/learning-from-books-dreamweaving/working_files/script.ssml
  files: []
