session_name: the-dragons-den-atmospheric-esoteric-journey-into-
topic: 'The Dragon''s Den: Atmospheric Esoteric Journey into Fire-Breathing Lore Dreamweaving'
topic_source: manual
mode: standard
duration_minutes: 30
audio_only: false
dry_run: false
execution:
  started: '2026-01-08T00:01:17.482250'
  ended: '2026-01-08T00:01:43.720777'
  duration_seconds: 26.2
stages:
  completed:
  - create_plan
  - create_session
  - generate_manifest
  failed:
  - generate_script
  - generate_script failed; aborting pipeline
  total: 5
costs:
  mode: standard
  multiplier: 1.0
  operations:
  - name: manifest_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2026-01-08T00:01:19.050720'
  - name: script_generation
    estimated: 0.35
    actual: 0.35
    timestamp: '2026-01-08T00:01:33.754595'
  total_usd: 0.4
outputs:
  session_path: /home/rsalars/Projects/dreamweaving/sessions/the-dragons-den-atmospheric-esoteric-journey-into-
  manifest: /home/rsalars/Projects/dreamweaving/sessions/the-dragons-den-atmospheric-esoteric-journey-into-/manifest.yaml
  script: /home/rsalars/Projects/dreamweaving/sessions/the-dragons-den-atmospheric-esoteric-journey-into-/working_files/script.ssml
  files: []
