session_name: eco-echo-conversations-with-nature
topic: 'Eco Echo: Conversations with Nature'
topic_source: manual
mode: standard
duration_minutes: 30
audio_only: false
dry_run: false
execution:
  started: '2026-01-20T01:00:14.677236'
  ended: '2026-01-20T01:27:07.921842'
  duration_seconds: 1613.2
stages:
  completed:
  - create_plan
  - create_session
  - generate_manifest
  - generate_script
  - generate_prompts
  - generate_voice
  - generate_binaural
  - generate_sfx
  - mix_audio
  - hypnotic_post_process
  - generate_vtt
  - generate_images
  - assemble_video
  - generate_thumbnail
  - upload_website
  - self_improvement
  failed: []
  total: 16
costs:
  mode: standard
  multiplier: 1.0
  operations:
  - name: manifest_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2026-01-20T01:00:16.307386'
  - name: script_generation
    estimated: 0.35
    actual: 0.35
    timestamp: '2026-01-20T01:00:30.106422'
  - name: image_prompts
    estimated: 0.1
    actual: 0.1
    timestamp: '2026-01-20T01:02:18.912197'
  - name: voice_synthesis
    estimated: 0.15
    actual: 0.15
    timestamp: '2026-01-20T01:02:18.962875'
  - name: vtt_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2026-01-20T01:12:13.968206'
  total_usd: 0.7
outputs:
  session_path: /home/rsalars/Projects/dreamweaving/sessions/eco-echo-conversations-with-nature
  manifest: /home/rsalars/Projects/dreamweaving/sessions/eco-echo-conversations-with-nature/manifest.yaml
  script: /home/rsalars/Projects/dreamweaving/sessions/eco-echo-conversations-with-nature/working_files/script.ssml
  files:
  - output/eco_echo_conversations_with_nature_MASTER.mp3
  - output/subtitles.vtt
  - output/voice.mp3
  - output/sfx.wav
  - output/seo_metadata.json
  - output/youtube_thumbnail.png
  - output/eco_echo_conversations_with_nature_MASTER.wav
  - output/session_mixed.wav
  - output/binaural_dynamic.wav
  - output/product_schema.json
