session_name: mother-gaias-guidance-deepening-our-connection-to-
topic: 'Mother Gaia''s Guidance: Deepening our Connection to Earth through Pagan Dreamweaving'
topic_source: manual
mode: standard
duration_minutes: 30
audio_only: false
dry_run: false
execution:
  started: '2026-01-08T00:00:03.579333'
  ended: '2026-01-08T00:00:47.705657'
  duration_seconds: 44.1
stages:
  completed:
  - create_plan
  - create_session
  - generate_manifest
  failed:
  - generate_script
  - generate_script failed; aborting pipeline
  total: 5
costs:
  mode: standard
  multiplier: 1.0
  operations:
  - name: manifest_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2026-01-08T00:00:05.110197'
  - name: script_generation
    estimated: 0.35
    actual: 0.35
    timestamp: '2026-01-08T00:00:35.457612'
  total_usd: 0.4
outputs:
  session_path: /home/rsalars/Projects/dreamweaving/sessions/mother-gaias-guidance-deepening-our-connection-to-
  manifest: /home/rsalars/Projects/dreamweaving/sessions/mother-gaias-guidance-deepening-our-connection-to-/manifest.yaml
  script: /home/rsalars/Projects/dreamweaving/sessions/mother-gaias-guidance-deepening-our-connection-to-/working_files/script.ssml
  files: []
