session_name: inner-peace-meditation-20251204
topic: Inner Peace Meditation
mode: standard
duration_minutes: 30
audio_only: true
dry_run: false
execution:
  started: '2025-12-04T05:51:33.471736'
  ended: '2025-12-04T05:54:04.206637'
  duration_seconds: 150.7
stages:
  completed:
  - create_session
  - generate_manifest
  - generate_script
  - generate_prompts
  - generate_vtt
  - self_improvement
  failed:
  - generate_voice
  total: 7
costs:
  mode: standard
  multiplier: 1.0
  operations:
  - name: manifest_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2025-12-04T05:51:33.473006'
  - name: script_generation
    estimated: 0.35
    actual: 0.35
    timestamp: '2025-12-04T05:51:33.488300'
  - name: image_prompts
    estimated: 0.1
    actual: 0.1
    timestamp: '2025-12-04T05:53:19.360992'
  - name: voice_synthesis
    estimated: 0.15
    actual: 0.15
    timestamp: '2025-12-04T05:53:19.412604'
  - name: vtt_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2025-12-04T05:54:04.135700'
  total_usd: 0.7
outputs:
  session_path: /home/rsalars/Projects/dreamweaving/sessions/inner-peace-meditation-20251204
  manifest: /home/rsalars/Projects/dreamweaving/sessions/inner-peace-meditation-20251204/manifest.yaml
  script: /home/rsalars/Projects/dreamweaving/sessions/inner-peace-meditation-20251204/working_files/script.ssml
  files:
  - output/subtitles.vtt
