session_name: tiamats-tide-surfing-the-primordial-chaos-in-cosmi
topic: 'Tiamat''s Tide: Surfing the Primordial Chaos in Cosmic Babylonian Dreamweaving'
topic_source: manual
mode: standard
duration_minutes: 30
audio_only: false
dry_run: false
execution:
  started: '2026-01-30T01:17:07.738409'
  ended: '2026-01-30T01:44:34.986095'
  duration_seconds: 1647.2
stages:
  completed:
  - create_plan
  - create_session
  - generate_manifest
  - generate_script
  - generate_prompts
  - generate_voice
  - generate_binaural
  - generate_sfx
  - mix_audio
  - hypnotic_post_process
  - generate_vtt
  - generate_images
  - assemble_video
  - generate_thumbnail
  - upload_website
  - self_improvement
  failed: []
  total: 16
costs:
  mode: standard
  multiplier: 1.0
  operations:
  - name: manifest_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2026-01-30T01:17:09.459773'
  - name: script_generation
    estimated: 0.35
    actual: 0.35
    timestamp: '2026-01-30T01:17:22.736738'
  - name: image_prompts
    estimated: 0.1
    actual: 0.1
    timestamp: '2026-01-30T01:19:09.811643'
  - name: voice_synthesis
    estimated: 0.15
    actual: 0.15
    timestamp: '2026-01-30T01:19:09.869740'
  - name: vtt_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2026-01-30T01:31:05.459139'
  total_usd: 0.7
outputs:
  session_path: /home/rsalars/Projects/dreamweaving/sessions/tiamats-tide-surfing-the-primordial-chaos-in-cosmi
  manifest: /home/rsalars/Projects/dreamweaving/sessions/tiamats-tide-surfing-the-primordial-chaos-in-cosmi/manifest.yaml
  script: /home/rsalars/Projects/dreamweaving/sessions/tiamats-tide-surfing-the-primordial-chaos-in-cosmi/working_files/script.ssml
  files:
  - output/tiamats_tide_surfing_the_primordial_chaos_in_cosmi_MASTER.mp3
  - output/subtitles.vtt
  - output/voice.mp3
  - output/tiamats_tide_surfing_the_primordial_chaos_in_cosmi_MASTER.wav
  - output/sfx.wav
  - output/seo_metadata.json
  - output/youtube_thumbnail.png
  - output/session_mixed.wav
  - output/binaural_dynamic.wav
  - output/product_schema.json
