session_name: reversing-the-tree-a-uniquely-puzzling-journey-up-
topic: 'Reversing the Tree: A Uniquely Puzzling Journey Up the Qabalistic Tree'
topic_source: manual
mode: standard
duration_minutes: 30
audio_only: false
dry_run: false
execution:
  started: '2026-01-12T00:58:25.092433'
  ended: '2026-01-12T01:40:57.990042'
  duration_seconds: 2552.9
stages:
  completed:
  - create_plan
  - create_session
  - generate_manifest
  - generate_script
  - generate_prompts
  - generate_voice
  - generate_binaural
  - generate_sfx
  - mix_audio
  - hypnotic_post_process
  - generate_vtt
  - generate_images
  - assemble_video
  - generate_thumbnail
  - upload_website
  - self_improvement
  failed: []
  total: 16
costs:
  mode: standard
  multiplier: 1.0
  operations:
  - name: manifest_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2026-01-12T00:58:26.955326'
  - name: script_generation
    estimated: 0.35
    actual: 0.35
    timestamp: '2026-01-12T00:58:40.110659'
  - name: image_prompts
    estimated: 0.1
    actual: 0.1
    timestamp: '2026-01-12T01:00:36.649896'
  - name: voice_synthesis
    estimated: 0.15
    actual: 0.15
    timestamp: '2026-01-12T01:00:36.712267'
  - name: vtt_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2026-01-12T01:19:38.756038'
  total_usd: 0.7
outputs:
  session_path: /home/rsalars/Projects/dreamweaving/sessions/reversing-the-tree-a-uniquely-puzzling-journey-up-
  manifest: /home/rsalars/Projects/dreamweaving/sessions/reversing-the-tree-a-uniquely-puzzling-journey-up-/manifest.yaml
  script: /home/rsalars/Projects/dreamweaving/sessions/reversing-the-tree-a-uniquely-puzzling-journey-up-/working_files/script.ssml
  files:
  - output/subtitles.vtt
  - output/reversing_the_tree_a_uniquely_puzzling_journey_up__MASTER.mp3
  - output/voice.mp3
  - output/sfx.wav
  - output/seo_metadata.json
  - output/youtube_thumbnail.png
  - output/session_mixed.wav
  - output/binaural_dynamic.wav
  - output/product_schema.json
  - output/reversing_the_tree_a_uniquely_puzzling_journey_up__MASTER.wav
