session_name: the-crystal-cavern-of-cellular-memory-jo-20251206
topic: 'The Crystal Cavern of Cellular Memory-Journey: Explore a cavern where crystals
  resonate with cellular memory; archetypes facilitate releasing old trauma and embedding
  vitality. | Archetypes:** The Crystal Keeper, The Healer, The Observer Self'
mode: standard
duration_minutes: 30
audio_only: false
dry_run: false
execution:
  started: '2025-12-06T09:58:36.098998'
  ended: '2025-12-06T10:04:11.576826'
  duration_seconds: 335.5
stages:
  completed:
  - create_session
  - generate_manifest
  - generate_script
  - generate_prompts
  - generate_voice
  - generate_binaural
  - mix_audio
  - hypnotic_post_process
  - generate_vtt
  - package_youtube
  - upload_website
  - cleanup
  - self_improvement
  failed: []
  total: 13
costs:
  mode: standard
  multiplier: 1.0
  operations:
  - name: manifest_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2025-12-06T09:58:36.099438'
  - name: script_generation
    estimated: 0.35
    actual: 0.35
    timestamp: '2025-12-06T09:58:36.116662'
  - name: image_prompts
    estimated: 0.1
    actual: 0.1
    timestamp: '2025-12-06T09:59:36.496077'
  - name: voice_synthesis
    estimated: 0.15
    actual: 0.15
    timestamp: '2025-12-06T09:59:36.553608'
  - name: vtt_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2025-12-06T10:03:49.560432'
  total_usd: 0.7
outputs:
  session_path: /home/rsalars/Projects/dreamweaving/sessions/the-crystal-cavern-of-cellular-memory-jo-20251206
  manifest: /home/rsalars/Projects/dreamweaving/sessions/the-crystal-cavern-of-cellular-memory-jo-20251206/manifest.yaml
  script: /home/rsalars/Projects/dreamweaving/sessions/the-crystal-cavern-of-cellular-memory-jo-20251206/working_files/script.ssml
  files:
  - output/the_crystal_cavern_of_cellular_memory_jo_20251206_MASTER.mp3
  - output/subtitles.vtt
