# Dreamweaving Project Configuration for Serena
# Sacred Digital Dreamweaver - Hypnotic audio/video session production workflow

# ==============================================================================
# LANGUAGE SERVER PREREQUISITES
# ==============================================================================
# Serena's semantic tools (find_symbol, replace_symbol_body, etc.) require
# language servers to be installed BEFORE starting the MCP server.
#
# Required installations (run once):
#   pipx install python-lsp-server          # For Python
#   npm install --prefix ~/.local bash-language-server yaml-language-server
#   ln -sf ~/.local/node_modules/.bin/bash-language-server ~/.local/bin/
#   ln -sf ~/.local/node_modules/.bin/yaml-language-server ~/.local/bin/
#
# Verify with:
#   which pylsp bash-language-server yaml-language-server
#
# If you see "language server manager is not initialized":
#   1. Install missing language servers (above)
#   2. Restart VS Code to restart Serena MCP servers
#   3. Or manually restart Serena processes
# ==============================================================================

# Languages for which language servers are started
# Python for the audio/video scripts, bash for shell scripts, yaml for manifests
languages:
- python
- bash
- yaml

# Text file encoding
encoding: "utf-8"

# Use gitignore to ignore files
ignore_all_files_in_gitignore: true

# Additional paths to ignore
ignored_paths:
- "temp_audio/**"
- "test_output/**"
- "**/*.wav"
- "**/*.mp3"
- "**/*.mp4"
- "**/*.aac"
- "**/*.png"
- "**/*.jpg"
- "**/*.jpeg"

# whether the project is in read-only mode
# If set to true, all editing tools will be disabled and attempts to use them will result in an error
# Added on 2025-04-18
read_only: false

# No tools excluded
excluded_tools: []

# Initial prompt for this project
initial_prompt: |
  This is the Dreamweaving project - a workflow for producing hypnotic audio/video sessions.

  Key directories:
  - scripts/core/ - Main production scripts (audio generation, mastering, video assembly)
  - scripts/utilities/ - Helper scripts (validation, environment setup)
  - sessions/ - Individual session content (manifests, scripts, images, audio)
  - docs/ - Documentation
  - prompts/ - Hypnotic technique guidelines

  Key concepts:
  - Sessions are defined by manifest.yaml files
  - Voice scripts use SSML format
  - Audio layers include binaural beats, pink noise, nature sounds, and voice
  - Voice enhancement applies psychoacoustic processing (warmth, de-essing, whisper overlay, etc.)
# the name by which the project can be referenced within Serena
project_name: "dreamweaving"

# ==============================================================================
# Dreamweaver-Specific Memories
# ==============================================================================
# These memories contain critical workflows and methodologies for the project.
# Claude should read relevant memories before starting work on specific tasks.
#
# Available memories:
#   - dreamweaver_journey_design: Complete methodology for designing hypnotic journeys
#   - audio_production_methodology: Mixing levels, mastering, stem handling
#   - script_production_workflow: SSML writing, section structure, voice pacing
#   - voice_pacing_guidelines: Quick reference for prosody and breaks
#   - session_learnings_system: Lessons learned from past sessions
#   - dreamweaving_project_overview: Complete project architecture overview
#   - ai_os_implementation_complete: AI agent and command system documentation
#   - ai_creative_os_integration_plan: Future integration roadmap
#
# Memory reading priority by task type:
#   New Session:       dreamweaver_journey_design, session_learnings_system
#   Script Writing:    script_production_workflow, voice_pacing_guidelines
#   Audio Production:  audio_production_methodology
#   Code Changes:      dreamweaving_project_overview
#   Planning:          ai_creative_os_integration_plan

# ==============================================================================
# Dreamweaver Tool Workflows
# ==============================================================================
# The following workflow patterns are documented in CLAUDE.md under
# "Sacred Digital Dreamweaver – Serena MCP Framework":
#
# dreamweaver.generate_journey_outline:
#   - Use when starting a new session from a theme
#   - Generates structured sections with archetypes
#   - Saves to sessions/<slug>/outline.json
#
# dreamweaver.generate_ssml_section:
#   - Use when generating or revising SSML for a specific section
#   - Applies speech profiles (pitch, breaks) per section type
#   - ALWAYS use rate="1.0", never slow the rate
#
# dreamweaver.suggest_audio_bed:
#   - Use when designing binaural + ambience + SFX plan
#   - Generates frequency curves based on target state
#   - Saves to working_files/audio_plan.json
#
# dreamweaver.generate_youtube_package:
#   - Use when preparing session for YouTube publication
#   - Generates title, description, tags, chapters, thumbnail prompts
#   - Saves to youtube_package.md
#
# Python implementations in: scripts/ai/dreamweaver_tools.py

# ==============================================================================
# Session File Structure Reference
# ==============================================================================
# Each session follows this structure:
#
# sessions/<session-slug>/
# ├── manifest.yaml              # Session configuration
# ├── outline.json               # Structured journey outline
# ├── notes.md                   # Design notes and changelog
# ├── midjourney-prompts.md      # Image generation prompts
# ├── youtube_package.md         # Publication package
# ├── working_files/
# │   ├── script_production.ssml # Full SSML with SFX markers
# │   ├── script_voice_clean.ssml# TTS-ready script (no SFX)
# │   ├── script_sections/       # Per-section SSML files
# │   └── audio_plan.json        # Binaural + FX timeline
# ├── images/uploaded/           # User-provided PNGs
# └── output/
#     ├── voice_enhanced.mp3     # USE THIS for production
#     ├── binaural_dynamic.wav
#     ├── sfx_track.wav
#     ├── session_mixed.wav
#     └── final_master.mp3

# ==============================================================================
# Critical Production Rules
# ==============================================================================
# 1. SSML: Always use rate="1.0" - achieve pacing through <break> tags
# 2. Audio Levels: Voice -6dB, Binaural -6dB, SFX 0dB
# 3. Always use voice_enhanced.mp3, never raw voice.mp3
# 4. Validate SSML before TTS generation
# 5. Check venv is activated before running Python scripts
# 6. Read relevant Serena memories before starting work

# list of mode names to that are always to be included in the set of active modes
# The full set of modes to be activated is base_modes + default_modes.
# If the setting is undefined, the base_modes from the global configuration (serena_config.yml) apply.
# Otherwise, this setting overrides the global configuration.
# Set this to [] to disable base modes for this project.
# Set this to a list of mode names to always include the respective modes for this project.
base_modes:

# list of mode names that are to be activated by default.
# The full set of modes to be activated is base_modes + default_modes.
# If the setting is undefined, the default_modes from the global configuration (serena_config.yml) apply.
# Otherwise, this overrides the setting from the global configuration (serena_config.yml).
# This setting can, in turn, be overridden by CLI parameters (--mode).
default_modes:

# list of tools to include that would otherwise be disabled (particularly optional tools that are disabled by default)
included_optional_tools: []

# fixed set of tools to use as the base tool set (if non-empty), replacing Serena's default set of tools.
# This cannot be combined with non-empty excluded_tools or included_optional_tools.
fixed_tools: []
