session_name: the-amber-halls-of-serendipity-dreamweaving
topic: The Amber Halls Of Serendipity Dreamweaving
topic_source: manual
mode: standard
duration_minutes: 30
audio_only: false
dry_run: false
execution:
  started: '2026-01-14T01:08:57.373573'
  ended: '2026-01-14T01:46:38.282010'
  duration_seconds: 2260.9
stages:
  completed:
  - create_plan
  - create_session
  - generate_manifest
  - generate_script
  - generate_prompts
  - generate_voice
  - generate_binaural
  - generate_sfx
  - mix_audio
  - hypnotic_post_process
  - generate_vtt
  - generate_images
  - assemble_video
  - generate_thumbnail
  - upload_website
  - self_improvement
  failed: []
  total: 16
costs:
  mode: standard
  multiplier: 1.0
  operations:
  - name: manifest_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2026-01-14T01:08:59.098237'
  - name: script_generation
    estimated: 0.35
    actual: 0.35
    timestamp: '2026-01-14T01:09:11.341923'
  - name: image_prompts
    estimated: 0.1
    actual: 0.1
    timestamp: '2026-01-14T01:11:13.757797'
  - name: voice_synthesis
    estimated: 0.15
    actual: 0.15
    timestamp: '2026-01-14T01:11:13.817459'
  - name: vtt_generation
    estimated: 0.05
    actual: 0.05
    timestamp: '2026-01-14T01:29:02.921597'
  total_usd: 0.7
outputs:
  session_path: /home/rsalars/Projects/dreamweaving/sessions/the-amber-halls-of-serendipity-dreamweaving
  manifest: /home/rsalars/Projects/dreamweaving/sessions/the-amber-halls-of-serendipity-dreamweaving/manifest.yaml
  script: /home/rsalars/Projects/dreamweaving/sessions/the-amber-halls-of-serendipity-dreamweaving/working_files/script.ssml
  files:
  - output/the_amber_halls_of_serendipity_dreamweaving_MASTER.wav
  - output/subtitles.vtt
  - output/voice.mp3
  - output/the_amber_halls_of_serendipity_dreamweaving_MASTER.mp3
  - output/sfx.wav
  - output/seo_metadata.json
  - output/youtube_thumbnail.png
  - output/session_mixed.wav
  - output/binaural_dynamic.wav
  - output/product_schema.json
